A.6.4.0400 - Draft Mode
vanderbilt-redcap/redcap_rsvc pull request #170
Opened 2024-12-20 15:27 UTC by MintooXavier

Added steps to verify the instrument reflects the changes done in Draft Mode.

I have used a new CDISC file A64400.xml as Project_1.xml contains another radio field with the same options and hence cannot verify the changes.

A64400.xml : https://github.com/4bbakers/redcap_rsvc/blob/MX_v14.7.0/Files/cdisc_files/A64400.xml

2024-12-20 16:24 UTC, mmcev106 requested changes
@MintooXavier, conceptually this makes sense to me.  However, it conflicts with our goal of minimizing the number of XML files.  I think there are many ways this could be done with `Project_1.xml` or one of our other XML files.  It could be a very simple change, like renaming a field, or adding a new field or instrument.  If those suggestions make sense, but you're not interested or able to implement them, I'd be happy to do it.  What are your thoughts?

2025-01-06 17:42 UTC, mmcev106 commented
This feature is currently passing in cloud build 2021:

![image](https://github.com/user-attachments/assets/a9201269-1f11-402d-8576-294306a60bad)

The issue for this feature was closed a few weeks ago, but I will leave this PR open as an improvement suggestion.

2025-01-06 18:25 UTC, MintooXavier commented
Agree.. we could add this with the modifications you suggested in the next iteration.. Apologies for late response.. I was off for 2 weeks..

2025-03-04 17:09 UTC, 4bbakers commented
Is this feature currently passing automation?

2025-03-04 17:23 UTC, mmcev106 commented
@4bbakers, the version of this feature (before this PR) is passing automation.  This is one of the cleanup tasks on my TODO list.  Do you have an opinion on these proposed changes?

2025-04-02 11:57 UTC, closed without merging